### ISSUE TITLE
Review convertRaDec class

### ISSUE THREAD

**Issue by steelewool** [steelewool/cgem-controller#11]
@zcsteele when you get a chance could you review the convertRaDecToCgemUnits class? The copy I need to review lives in the branch 'addMethodsToConverClass'. If you think it looks OK I'll merge the branch.

**Comment by steelewool** [comment]
We may not need to branch this one if the work in setupTestForCommandCgem captures all of the desired changes.

**Comment by zcsteele** [comment]
@RobSteele49 can you make a pull request from that branch?

**Comment by steelewool** [comment]
Done - but there were conflicts.

**Comment by steelewool** [comment]
@zcsteele This looks like one we should chat about.

**Comment by steelewool** [comment]
Looks like no longer a concern so I'm closing this issue.
