### ISSUE TITLE
Fix size of output strings

### ISSUE THREAD

**Issue by steelewool** [steelewool/cgem-controller#16]
The ASCII commands sent to the hand controller require a very fixed widths. I need leading zeros inserted for values don't take up all 6 hex positions. I'm having to add '00' to the end of the position commands as well.

**Comment by zcsteele** [comment]
We could make a separate object with serial I/O and command logic bundled together, and have the padding operations standardized there.

**Comment by steelewool** [comment]
If you have time to do that today, that would be great, I've got pool filter duty and moving the control for the tankless water heater on my plate.

**Comment by steelewool** [comment]
This needs to be tested for the entire range of the RA and Declination values.

**Comment by steelewool** [comment]
The current version of the convert module resolves this issue so I'll close it for now. We can re-open or create new issues if there is a need.
