### ISSUE TITLE
Change Output to UPPER CASE

### ISSUE THREAD

**Issue by steelewool** [steelewool/cgem-controller#23]
Just to make things easier to compare with the  output from the hand controller is their an 'easy' way to change the output strings that are being sent to the hand controller to upper cases. That is instead of 'ab' we would send 'AB'.

**Comment by steelewool** [comment]
Fixed this in my new branch returnUpperCaseFromtoCgem to fix this and it is ready to merge if that won't affect you negatively.

**Comment by zcsteele** [comment]
Closing this as the code has been merged to `master`
