### ISSUE TITLE
Zach: Do you need a serial cable (one, two, null modem, and gender bender)

### ISSUE THREAD

**Issue by steelewool** [steelewool/cgem-controller#25]
Would having a serial cable, that you could configure as a loop back test help you? Or would you need a 2nd cable to act as the hand controllers. If you had two you would need a null modem to put between the two cables connected to two of your USB ports. Of course this would mean extra software to write. Let me know as I have an extra one here at the house.

To set up a loop back I need to change the sex of the cable, since the one I have is a male and the female connector is easier to setup as a loop back with hay wires.

**Comment by zcsteele** [comment]
I've found some software that should be usable for serial port testing locally, without needing any test hardware.  I'll let you know how my test run goes.

**Comment by steelewool** [comment]
That would be great for both of us. Let me know how the testing of this goes.

**Comment by zcsteele** [comment]
I'm closing this issue for now; I have a working demo of a virtual null modem so we don't need to build loopback adapters.
