### ISSUE TITLE
Build a simulator of the CGEM

### ISSUE THREAD

**Issue by steelewool** [steelewool/cgem-controller#30]
Based on what Zach learns from #25 we might be able to build a simple simulator to test with. This would save me from using telescope time for debugging. The simulator could be pretty easy based on the ICD. I would have to of course verify it against actually commands. But that  is covered in a separate issue - item number #28.

**Comment by zcsteele** [comment]
@RobSteele49 I have a branch set up with my first successful pass at using a virtual null modem:
https://github.com/steelewool/cgem-controller/tree/null-modem

We can discuss my next steps later when you have time to chat.

**Comment by steelewool** [comment]
Rob got in and added some code to the simulator. What I did to run this:
In one window: ./null-modem
in a second window: python simulator.py
In a third window python cgemObserveMessierObjects.py

The output did look a little wierd from cgemObserveMessierObjects:

Read :  a#
meanLST                      :  16h58m07.1209s
16 58 7
M 103
   Bin number      : 1
   Name            : M  82
   RA   hr min sec : 09:55:52
   Dec deg min sec : +69:40:52
   Local Hour Angle: -7
   LST  hr min sec : 16:58:7

1 to observe, 2 to skip, 3 to exit 1
gotoCommand : r69EE8D00,318CCD00
Result of L command:  ##
Result of L command:  0#
Goto Finished
result ra/dec:  0
   Bin number      : 1
   Name            : M  81
   RA   hr min sec : 09:55:33
   Dec deg min sec : +69:03:33
   Local Hour Angle: -7
   LST  hr min sec : 16:58:7

1 to observe, 2 to skip, 3 to exit 1
gotoCommand : r69E02400,311CF400
Result of L command:  ##
Result of L command:  0#
Goto Finished

The result of ## and 0# were not what I had expected.

From null modem the output looked like:

steele@steele:~/git/steelewool/cgem-controller$ ./nullmodem.sh 
2018/10/01 17:02:09 socat[6336] N PTY is /dev/pts/0
2018/10/01 17:02:09 socat[6336] N PTY is /dev/pts/1
  FD  type	device	inode	mode	links	uid	gid	rdev	size	blksize	blocks	atime			mtime				ctime				cloexec	flags	sigown	sigio
   5: chrdev	0,6	86	020666	1	0	5	5,2	0	4096	0	Mon Oct  1 17:02:08 2018	Mon Oct  1 17:02:08 2018	Mon Oct  1 05:50:23 2018	1	x008002	0	0	(no STREAMS modules)	/dev/ptmx 	IFLAGS=00000000 OFLAGS=00000004 CFLAGS=000000bd LFLAGS=00000a30 cc[0]=^C cc[1]=^\ cc[2]=x7F cc[3]=^U cc[4]=^D cc[5]=^@ cc[6]=^A cc[7]=^@ cc[8]=^Q cc[9]=^S cc[10]=^Z cc[11]=^@ cc[12]=^R cc[13]=^O cc[14]=^W cc[15]=^V cc[16]=^@ cc[17]=^@ cc[18]=^@ cc[19]=^@ cc[20]=^@ cc[21]=^@ cc[22]=^@ cc[23]=^@ cc[24]=^@ cc[25]=^@ cc[26]=^@ cc[27]=^@ cc[28]=^@ cc[29]=^@ cc[30]=^@ cc[31]=^@poll: OUT,
   7: chrdev	0,6	86	020666	1	0	5	5,2	0	4096	0	Mon Oct  1 17:02:08 2018	Mon Oct  1 17:02:08 2018	Mon Oct  1 05:50:23 2018	1	x008002	0	0	(no STREAMS modules)	/dev/ptmx 	IFLAGS=00000000 OFLAGS=00000004 CFLAGS=000000bd LFLAGS=00000a30 cc[0]=^C cc[1]=^\ cc[2]=x7F cc[3]=^U cc[4]=^D cc[5]=^@ cc[6]=^A cc[7]=^@ cc[8]=^Q cc[9]=^S cc[10]=^Z cc[11]=^@ cc[12]=^R cc[13]=^O cc[14]=^W cc[15]=^V cc[16]=^@ cc[17]=^@ cc[18]=^@ cc[19]=^@ cc[20]=^@ cc[21]=^@ cc[22]=^@ cc[23]=^@ cc[24]=^@ cc[25]=^@ cc[26]=^@ cc[27]=^@ cc[28]=^@ cc[29]=^@ cc[30]=^@ cc[31]=^@poll: OUT,
2018/10/01 17:02:09 socat[6336] N starting data transfer loop with FDs [5,5] and [7,7]
< 2018/10/01 17:02:19.935153  length=2 from=0 to=1
Ka> 2018/10/01 17:03:36.445531  length=2 from=0 to=1
Ka< 2018/10/01 17:03:36.445933  length=2 from=2 to=3
a#> 2018/10/01 17:05:21.441216  length=18 from=2 to=19
r69EE8D00,318CCD00< 2018/10/01 17:05:22.443885  length=1 from=4 to=4
#> 2018/10/01 17:05:23.443930  length=1 from=20 to=20
L< 2018/10/01 17:05:23.444261  length=2 from=5 to=6
0#> 2018/10/01 17:05:24.448686  length=1 from=21 to=21
L< 2018/10/01 17:05:24.449327  length=2 from=7 to=8
0#> 2018/10/01 17:05:25.451926  length=1 from=22 to=22
L< 2018/10/01 17:05:25.452563  length=2 from=9 to=10
0#> 2018/10/01 17:05:26.455367  length=1 from=23 to=23
L< 2018/10/01 17:05:26.455857  length=2 from=11 to=12
0#> 2018/10/01 17:05:27.458753  length=1 from=24 to=24
L< 2018/10/01 17:05:27.459314  length=2 from=13 to=14
0#> 2018/10/01 17:05:28.461189  length=1 from=25 to=25
L< 2018/10/01 17:05:28.461583  length=2 from=15 to=16
0#> 2018/10/01 17:05:29.463064  length=1 from=26 to=26
L< 2018/10/01 17:05:29.463393  length=2 from=17 to=18
0#> 2018/10/01 17:05:30.465293  length=1 from=27 to=27
L< 2018/10/01 17:05:30.465857  length=2 from=19 to=20
0#> 2018/10/01 17:05:31.468369  length=1 from=28 to=28
L< 2018/10/01 17:05:31.468606  length=2 from=21 to=22
0#> 2018/10/01 17:05:32.469756  length=1 from=29 to=29
L< 2018/10/01 17:05:32.470412  length=2 from=23 to=24
0#> 2018/10/01 17:05:33.471663  length=1 from=30 to=30
L< 2018/10/01 17:05:33.472243  length=2 from=25 to=26
0#> 2018/10/01 17:05:34.477581  length=1 from=31 to=31
L> 2018/10/01 17:05:36.479935  length=1 from=32 to=32
L> 2018/10/01 17:05:38.481488  length=1 from=33 to=33
L> 2018/10/01 17:05:40.483738  length=1 from=34 to=34
L> 2018/10/01 17:06:26.290656  length=2 from=35 to=36
Ka< 2018/10/01 17:06:26.290947  length=2 from=27 to=28
a#> 2018/10/01 17:06:34.604660  length=18 from=37 to=54
r69EE8D00,318CCD00< 2018/10/01 17:06:35.607344  length=1 from=29 to=29
#> 2018/10/01 17:06:36.606457  length=1 from=55 to=55
L< 2018/10/01 17:06:36.607008  length=2 from=30 to=31
0#> 2018/10/01 17:06:37.608943  length=1 from=56 to=56
L< 2018/10/01 17:06:37.609481  length=2 from=32 to=33
0#> 2018/10/01 17:06:38.615580  length=1 from=57 to=57
L< 2018/10/01 17:06:38.616140  length=2 from=34 to=35
0#> 2018/10/01 17:06:39.621176  length=1 from=58 to=58
L< 2018/10/01 17:06:39.621687  length=2 from=36 to=37
0#> 2018/10/01 17:06:40.623742  length=1 from=59 to=59
L< 2018/10/01 17:06:40.624169  length=2 from=38 to=39
0#> 2018/10/01 17:06:41.628814  length=1 from=60 to=60
L< 2018/10/01 17:06:41.628985  length=2 from=40 to=41
0#> 2018/10/01 17:07:25.864162  length=2 from=61 to=62
Ka< 2018/10/01 17:07:25.864391  length=2 from=42 to=43
a#> 2018/10/01 17:07:30.062688  length=18 from=63 to=80
r69EE8D00,318CCD00< 2018/10/01 17:07:31.080473  length=1 from=44 to=44
#> 2018/10/01 17:07:32.118817  length=1 from=81 to=81
L< 2018/10/01 17:07:32.119307  length=2 from=45 to=46
#0> 2018/10/01 17:07:33.120057  length=1 from=82 to=82
L< 2018/10/01 17:07:33.120265  length=2 from=47 to=48
#0> 2018/10/01 17:07:33.120456  length=1 from=83 to=83
e> 2018/10/01 17:07:44.508440  length=18 from=84 to=101
r69E02400,311CF400< 2018/10/01 17:07:45.509890  length=1 from=49 to=49
#> 2018/10/01 17:07:46.512287  length=1 from=102 to=102
L< 2018/10/01 17:07:46.512952  length=2 from=50 to=51
#0> 2018/10/01 17:07:47.513590  length=1 from=103 to=103
L< 2018/10/01 17:07:47.513815  length=2 from=52 to=53
#0> 2018/10/01 17:07:47.513939  length=1 from=104 to=104
e^C2018/10/01 17:08:14 socat[6336] N socat_signal(): handling signal 2
2018/10/01 17:08:14 socat[6336] N exiting on signal 2
2018/10/01 17:08:14 socat[6336] N socat_signal(): finishing signal 2
2018/10/01 17:08:14 socat[6336] N exit(130)

**Comment by steelewool** [comment]
The telescope is using 9600 baud - is you simulator set up the same way?

**Comment by steelewool** [comment]
In my local copy of this branch I started to setup up a lastRa and lastDec whenever the telescope is commanded. This caused to bubble up that the fromCgem are returning a string and a tuple of hr, min, and sec looks more useful.

**Comment by zcsteele** [comment]
Another option would be to have `lastRa` and `lastDec` return new Ra/Dec objects (as currently defined in _convertRaDecToCgemUnits.py_) for later manipulation.

**Comment by steelewool** [comment]
Sounds like a good idea. I’ll move in that direction tonight.
