### ISSUE TITLE
Two RA and Dec objects in convertRaDectoCgem and objectRaDec module

### ISSUE THREAD

**Issue by steelewool** [steelewool/cgem-controller#57]
I'm not sure how to do this - but we should move to have just one Ra and Dec class to keep things from getting confusing. But this seem low priority compared to other things we are working on right now.

**Comment by zcsteele** [comment]
I'd like to move towards merging the two together, or at least streamlining the code so there's less duplication of code between the two.  PR #55 was a small step in that direction.

**Comment by steelewool** [comment]
To make debugging easier I'm kicking off the simulator from cgemObserverMessier.

**Comment by steelewool** [comment]
I created a raDecLst class that I attempting to use to replace the Ra, Dec, Lst, Azi, and Alt classes built in separate modules. But this isn't going well. I need to coordinate with Zach on any suggestions he might have. @zcsteele Any suggestions?

**Comment by steelewool** [comment]
Looks like I'm computing bin number incorrectly. This is based on a calculation involving subtraction for the LST class. This looks like where I need to be looking.

**Comment by steelewool** [comment]
looks like the python debugger may be helpful. To kick it off the syntax is: 'python -m pdb <pythonProgram>

**Comment by steelewool** [comment]
Still having trouble with the bin computation - but thee debugging looks really useful. Can set break points "b <line number>" and c. If the program terminates while debugging it is started over automatically.

**Comment by steelewool** [comment]
Merged the branch into main and closing the issue.
