### ISSUE TITLE
Testing 2018-10--08 Problem with read until

### ISSUE THREAD

**Issue by steelewool** [steelewool/cgem-controller#60]
WHen I tried using the code in the branch simulator on the scope there was an infinite loop in the read until logic. I moved over to the test branch and have commented out that logic.

**Comment by zcsteele** [comment]
@RobSteele49 I made a new branch with extra debug code - `debug-read-loop`.  Can you try running that copy of `cgemInterface.py` while interfacing with the telescope & send me the logs?
