### ISSUE TITLE
Test 2018-10-08 with Scope - problem with socat

### ISSUE THREAD

**Issue by steelewool** [steelewool/cgem-controller#61]
Probably just an operator error issue, but I could not get socat to pass commands from the telescope to the python program.

The command line I used:
socat -v -D -d -d PTY,link=./pty1 GOPEN:/dev/ttyUSB0

**Comment by zcsteele** [comment]
On my system, the TTY devices are all owned by root; Can you check `/dev/ttyUSB0`'s ownership while the telescope is connected?

Also, you may need to explicitly set the baud rate to mach what the serial device connection should be (9600).  Try this command after connecting the serial cable to both Pi and telescope:

```
sudo socat -v -D -d -d PTY,link=./pty1,b9600,cfmakeraw GOPEN:/dev/ttyUSB0,b9600,cfmakeraw
```

**Comment by steelewool** [comment]
The following worked on my Pi:

socat -v -D -d -d PTY,link=./pty1,b9600,cfmakeraw GOPEN:/dev/ttyUSB0,b9600,cfmakeraw

Which is the same, without the sudo command as what Zach suggessted. I'll put this on the wiki and then will close this issue.

**Comment by steelewool** [comment]
Created a wiki page with info about how to use socat.

https://github.com/steelewool/cgem-controller/wiki/Debugging-With-socat
